notifications:
  email: false

language: c

compiler:
  - gcc
  - clang

# Dependencies
addons:
  apt:
    source:
      - travic-ci/sqlite3
    packages:
      - sqlite3
      - libsqlite3-dev
      - libsqlite3-0

script:
  - make
