notifications:
  email: false

language: c

compiler:
  - clang

#FIXME:
# - gcc linking with sqlite doesn't work on travis with gcc

# Dependencies
addons:
  apt:
    source:
      - travic-ci/sqlite3
    packages:
      - sqlite3
      - libsqlite3-dev
      - libsqlite3-0

script:
  - make
