#           todo - Light TODO list
#        Copyright (C)  2012-2013 Heather

CC=gcc

CFLAGS=-O3 -Wall
CSRC=../contrib/sqlite/sqlite3.c ../ctodo.c ../cctodo.c
INCLUDES = -I ../contrib/sqlite
INSTALL   ?= install
MKDIR     ?= $(INSTALL) -d
BINDIR    ?= $(PREFIX)/bin
DESTDIR   ?=

all: cctodo

rebuild: all

cctodo:	$(CSRC)
	$(CC) ${INCLUDES} -o todo $^ ${CFLAGS}

.PHONY: clean all rebuild

install:
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) todo$(EXE) $(DESTDIR)$(BINDIR)/
